version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    postgres: